version: "4.2"

services:
  spring:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - postgres
    volumes:
      - .:/App
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=todoapi
    volumes:
      - pgdata:/var/lib/postgresql/data
  haproxy:
    image: haproxy
    ports:
      - "4444:4444"
      - "1905:1905"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

volumes:
  pgdata: