version: "4.2"

services:
  spring:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/App
    networks:
      - backend_network
    container_name: spring
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=todoapi
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network
  haproxy:
    image: haproxy
    depends_on:
      - spring
    ports:
      - "1905:1905"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  pgdata: